### ISSUE TITLE
NPM Build is not working

### ISSUE THREAD

**Issue by sarfarazengglb** [superbarne/feathers-chat-nuxt#1]
47700 silly saveTree   └── eyes@0.1.8
47701 verbose stack Error: node-sass@4.7.2 postinstall: `node scripts/build.js`
47701 verbose stack Exit status 1
47701 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
47701 verbose stack     at EventEmitter.emit (events.js:311:20)
47701 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
47701 verbose stack     at ChildProcess.emit (events.js:311:20)
47701 verbose stack     at maybeClose (internal/child_process.js:1021:16)
47701 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
47702 verbose pkgid node-sass@4.7.2
47703 verbose cwd /Users/mohammedsarfaraz/Projects/NodeProject/feathers-chat-nuxt
47704 verbose Darwin 17.7.0
47705 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
47706 verbose node v12.16.1
47707 verbose npm  v6.14.4
47708 error code ELIFECYCLE

**Comment by sarfarazengglb** [comment]
resolved
npm install node-sass --save-dev
Second error 
Unsupported platform for inotify@1.4.1: wanted {“os”:“linux”,“arch”:“any”}

resolved with below command 
npm install copy-webpack-plugin --save-dev
